-- Create schema
CREATE SCHEMA IF NOT EXISTS "APPLICATION_DATA";

-- CORE table (receiver)
CREATE TABLE IF NOT EXISTS "APPLICATION_DATA"."RESOURCE_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    path TEXT,
    method TEXT,
    headers JSONB,
    payload JSONB,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SMART POND
CREATE TABLE IF NOT EXISTS "APPLICATION_DATA"."SMART_POND_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    path TEXT,
    method TEXT,
    headers JSONB,
    payload JSONB,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SMART WATER
CREATE TABLE IF NOT EXISTS "APPLICATION_DATA"."SMART_WATER_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    path TEXT,
    method TEXT,
    headers JSONB,
    payload JSONB,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SMART WASTE
CREATE TABLE IF NOT EXISTS "APPLICATION_DATA"."SMART_WASTE_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    path TEXT,
    method TEXT,
    headers JSONB,
    payload JSONB,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SMART AGRI
CREATE TABLE IF NOT EXISTS "APPLICATION_DATA"."SMART_AGRI_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    path TEXT,
    method TEXT,
    headers JSONB,
    payload JSONB,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SMART EDU
CREATE TABLE IF NOT EXISTS "APPLICATION_DATA"."SMART_EDU_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    path TEXT,
    method TEXT,
    headers JSONB,
    payload JSONB,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
