CREATE SCHEMA IF NOT EXISTS "M2M_NOTIFICATIONS";

CREATE TABLE IF NOT EXISTS "M2M_NOTIFICATIONS"."RESOURCE_NOTIFICATION" (
    id SERIAL PRIMARY KEY,
    path TEXT,
    method TEXT,
    headers JSONB,
    payload JSONB,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
